import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const MOBILE_ROOT = "C:\\Users\\User\\.gemini\\AI coding\\smart_bus\\mobile_app";

async function readText(path) {
  return readFile(path, "utf8");
}

test("mobile Flutter workspace scaffold exists", async () => {
  const pubspec = await readText(`${MOBILE_ROOT}\\pubspec.yaml`);
  const mainDart = await readText(`${MOBILE_ROOT}\\lib\\main.dart`);
  const rootScreen = await readText(`${MOBILE_ROOT}\\lib\\features\\root\\mobile_root_screen.dart`);
  const authScreen = await readText(`${MOBILE_ROOT}\\lib\\features\\auth\\auth_workspace_screen.dart`);
  const operationsScreen = await readText(`${MOBILE_ROOT}\\lib\\features\\operations\\mobile_operations_screen.dart`);
  const apiClient = await readText(`${MOBILE_ROOT}\\lib\\core\\network\\mobile_api_client.dart`);
  const settingsStore = await readText(`${MOBILE_ROOT}\\lib\\core\\storage\\mobile_client_settings_store.dart`);
  const sessionStore = await readText(`${MOBILE_ROOT}\\lib\\core\\storage\\mobile_session_store.dart`);
  const androidGradle = await readText(`${MOBILE_ROOT}\\android\\app\\build.gradle.kts`);
  const androidReleaseKeyExample = await readText(`${MOBILE_ROOT}\\android\\key.properties.example`);
  const iosInfoPlist = await readText(`${MOBILE_ROOT}\\ios\\Runner\\Info.plist`);
  const webIndex = await readText(`${MOBILE_ROOT}\\web\\index.html`);
  const localProperties = await readText(`${MOBILE_ROOT}\\android\\local.properties`);
  const smokeTest = await readText(`${MOBILE_ROOT}\\test\\app_smoke_test.dart`);
  const previewSpec = await readText(`${MOBILE_ROOT}\\lib\\core\\device\\native_alarm_preview_spec.dart`);
  const previewService = await readText(`${MOBILE_ROOT}\\lib\\core\\device\\native_alarm_preview_service.dart`);
  const pushRuntime = await readText(`${MOBILE_ROOT}\\lib\\core\\device\\mobile_push_runtime.dart`);
  const pushPayload = await readText(`${MOBILE_ROOT}\\lib\\core\\device\\push_alarm_payload.dart`);
  const firebaseOptions = await readText(`${MOBILE_ROOT}\\lib\\firebase_options.dart`);
  const androidManifest = await readText(`${MOBILE_ROOT}\\android\\app\\src\\main\\AndroidManifest.xml`);
  const iosProject = await readText(`${MOBILE_ROOT}\\ios\\Runner.xcodeproj\\project.pbxproj`);
  const mobileScript = await readText(`C:\\Users\\User\\.gemini\\AI coding\\smart_bus\\scripts\\mobile-flutter.ps1`);
  const packageJson = await readText(`C:\\Users\\User\\.gemini\\AI coding\\smart_bus\\package.json`);

  assert.match(pubspec, /name:\s+buswakeup_mobile/);
  assert.match(pubspec, /audioplayers:\s+\^6\.8\.1/);
  assert.match(pubspec, /flutter_tts:\s+\^4\.2\.5/);
  assert.match(pubspec, /flutter_secure_storage:\s+\^10\.3\.1/);
  assert.match(pubspec, /shared_preferences:\s+\^2\.5\.5/);
  assert.match(pubspec, /vibration:\s+\^3\.2\.0/);
  assert.match(pubspec, /firebase_core:\s+\^4\.11\.0/);
  assert.match(pubspec, /firebase_messaging:\s+\^16\.4\.1/);
  assert.match(pubspec, /flutter_local_notifications:\s+\^22\.0\.1/);
  assert.match(pubspec, /assets\/audio\//);
  assert.match(androidGradle, /applicationId = "com\.buswakeup\.buswakeup_mobile"/);
  assert.match(androidGradle, /compileSdk = flutter\.compileSdkVersion/);
  assert.match(androidGradle, /isCoreLibraryDesugaringEnabled = true/);
  assert.match(androidGradle, /desugar_jdk_libs:2\.1\.4/);
  assert.match(androidGradle, /hasReleaseSigning/);
  assert.doesNotMatch(androidGradle, /signingConfig = signingConfigs\.getByName\("debug"\)/);
  assert.match(androidReleaseKeyExample, /keyAlias=/);
  assert.match(iosInfoPlist, /CFBundleDisplayName/);
  assert.match(iosInfoPlist, /remote-notification/);
  assert.match(iosProject, /IPHONEOS_DEPLOYMENT_TARGET = 15\.0/);
  assert.match(iosProject, /mechanical_alarm\.wav in Resources/);
  assert.match(androidManifest, /POST_NOTIFICATIONS/);
  assert.match(androidManifest, /buswakeup-critical/);
  assert.match(pushRuntime, /FirebaseMessaging\.onBackgroundMessage/);
  assert.match(pushRuntime, /requestPermissionAndGetToken/);
  assert.match(pushRuntime, /RawResourceAndroidNotificationSound\('mechanical_alarm'\)/);
  assert.match(pushRuntime, /mechanical_alarm\.wav/);
  assert.match(pushPayload, /buswakeup-critical/);
  assert.match(firebaseOptions, /flutterfire configure/);
  assert.match(webIndex, /BusWakeUp Mobile/);
  assert.match(localProperties, /flutter\.sdk=/);
  assert.match(localProperties, /sdk\.dir=/);
  assert.match(smokeTest, /BusWakeUpApp shows a bootstrap loading state first/);
  assert.match(smokeTest, /InMemorySharedPreferencesAsync\.empty/);
  assert.match(previewSpec, /이 버스 놓치면 지각이다\./);
  assert.match(previewSpec, /audio\/mechanical_alarm\.wav/);
  assert.match(previewService, /mechanical sound/);
  assert.match(previewService, /Korean TTS/);
  assert.match(mobileScript, /build-apk-debug/);
  assert.match(mobileScript, /build apk --debug/);
  assert.match(packageJson, /"mobile:doctor"/);
  assert.match(packageJson, /"mobile:build:apk:debug"/);
  assert.match(mainDart, /runApp\(const BusWakeUpApp\(\)\)/);
  assert.match(rootScreen, /_bootstrap\(\)/);
  assert.match(rootScreen, /restorePersistedBaseUrl/);
  assert.match(rootScreen, /restorePersistedSession/);
  assert.match(authScreen, /updateBaseUrlAndPersist/);
  assert.match(authScreen, /fetchMobileHealth/);
  assert.match(authScreen, /Save and check server/);
  assert.match(authScreen, /Checking server/);
  assert.match(authScreen, /Use default local URL/);
  assert.match(authScreen, /Server preflight/);
  assert.match(authScreen, /Reachability/);
  assert.match(authScreen, /Launch focus/);
  assert.match(authScreen, /Session probe/);
  assert.match(authScreen, /Push mode/);
  assert.match(authScreen, /Push lane/);
  assert.match(authScreen, /Recommended ETA order/);
  assert.match(authScreen, /Representative name or nickname/);
  assert.match(authScreen, /You can enter 192\.168\.0\.10:4173 and the app will add http:\/\/ automatically/);
  assert.match(authScreen, /For a real phone, use a LAN or HTTPS host instead of localhost/);
  assert.doesNotMatch(authScreen, /\?�\?�님/);
  assert.match(rootScreen, /AuthWorkspaceScreen/);
  assert.match(operationsScreen, /Commute setup/);
  assert.match(operationsScreen, /Save mobile setup/);
  assert.match(operationsScreen, /Search stations/);
  assert.match(operationsScreen, /Load route candidates/);
  assert.match(operationsScreen, /Accuracy matters more than API ownership/);
  assert.match(operationsScreen, /Manual TAGO binding: station search is disabled for this provider in the current mobile shell/);
  assert.match(operationsScreen, /Manual TAGO binding: route candidate lookup is disabled for this provider in the current mobile shell/);
  assert.match(operationsScreen, /Search the official Seoul stop first so the app can fill station id, ARS number, route id, and stop order for you/);
  assert.match(operationsScreen, /Binding mode/);
  assert.match(operationsScreen, /Search-assisted/);
  assert.match(operationsScreen, /Manual IDs/);
  assert.match(operationsScreen, /_providerSetupConfig/);
  assert.match(operationsScreen, /_supportsLiveStationRouteSearch/);
  assert.match(operationsScreen, /stationSearchSupported/);
  assert.match(operationsScreen, /stationRouteSearchSupported/);
  assert.match(operationsScreen, /bindingMode/);
  assert.match(operationsScreen, /bool enabled = true/);
  assert.match(operationsScreen, /String idleStatus = 'No search run yet.'/);
  assert.match(operationsScreen, /Home address matches/);
  assert.match(operationsScreen, /Station candidates/);
  assert.match(operationsScreen, /Bus ride minutes/);
  assert.match(operationsScreen, /Estimate walk and commute/);
  assert.match(operationsScreen, /Commute estimate/);
  assert.match(operationsScreen, /Register device token/);
  assert.match(operationsScreen, /Phone notification runtime/);
  assert.match(operationsScreen, /Enable and register this phone/);
  assert.match(operationsScreen, /Server endpoint/);
  assert.match(operationsScreen, /API base URL/);
  assert.match(operationsScreen, /Apply server URL/);
  assert.match(operationsScreen, /Reload from server/);
  assert.match(operationsScreen, /Run server health check/);
  assert.match(operationsScreen, /Server health/);
  assert.match(operationsScreen, /Launch focus/);
  assert.match(operationsScreen, /Push lane/);
  assert.match(operationsScreen, /Launch verdict/);
  assert.match(operationsScreen, /Immediate server fix/);
  assert.match(operationsScreen, /Why this matters/);
  assert.match(operationsScreen, /Launch checklist/);
  assert.match(operationsScreen, /LOCALHOST MISMATCH RISK/);
  assert.match(operationsScreen, /LAN TEST MODE/);
  assert.match(operationsScreen, /GATEWAY AUTH BLOCKED/);
  assert.match(operationsScreen, /READY FOR REAL-DEVICE TEST/);
  assert.match(operationsScreen, /Use LAN host checklist/);
  assert.match(operationsScreen, /Refresh gateway health/);
  assert.match(operationsScreen, /Start real test push flow/);
  assert.match(operationsScreen, /Real-device push test flow/);
  assert.match(operationsScreen, /Step 1 - Register token/);
  assert.match(operationsScreen, /Step 2 - Check permissions/);
  assert.match(operationsScreen, /Step 3 - Confirm readiness/);
  assert.match(operationsScreen, /Step 4 - Run test push/);
  assert.match(operationsScreen, /Current step/);
  assert.match(operationsScreen, /Why paused/);
  assert.match(operationsScreen, /Operator hint/);
  assert.match(operationsScreen, /Resume guide/);
  assert.match(operationsScreen, /Last completed step/);
  assert.match(operationsScreen, /Last completed status/);
  assert.match(operationsScreen, /Completed at/);
  assert.match(operationsScreen, /Checkpoint detail/);
  assert.match(operationsScreen, /Refresh flow status/);
  assert.match(operationsScreen, /Reset saved progress/);
  assert.match(operationsScreen, /Run test push now/);
  assert.match(operationsScreen, /Run readiness checks/);
  assert.match(operationsScreen, /Continue with Step 2 permission review/);
  assert.match(operationsScreen, /Continue with Step 3 readiness checks/);
  assert.match(operationsScreen, /Continue with Step 4 test push/);
  assert.match(operationsScreen, /Repeat Step 4 test push/);
  assert.match(operationsScreen, /No saved progress yet/);
  assert.match(operationsScreen, /Saved progress ended at/);
  assert.match(operationsScreen, /Saved progress already covers this stage/);
  assert.match(operationsScreen, /Use the token currently issued by Firebase or APNs on this phone/);
  assert.match(operationsScreen, /Health check, token health, gateway credentials, and preview readiness must all line up before Step 4/);
  assert.match(operationsScreen, /DONE WITH WARNINGS/);
  assert.doesNotMatch(operationsScreen, /·/);
  assert.match(operationsScreen, /updateBaseUrlAndPersist/);
  assert.match(operationsScreen, /Push launch readiness/);
  assert.match(operationsScreen, /Launch blockers/);
  assert.match(operationsScreen, /Readiness state/);
  assert.match(operationsScreen, /Next step/);
  assert.match(operationsScreen, /Adapter lane/);
  assert.match(operationsScreen, /Preview state/);
  assert.match(operationsScreen, /Gateway attempt/);
  assert.match(operationsScreen, /Hard blockers/);
  assert.match(operationsScreen, /Warnings/);
  assert.match(operationsScreen, /Top blocker/);
  assert.match(operationsScreen, /Fallback safety/);
  assert.match(operationsScreen, /Warning summary/);
  assert.match(operationsScreen, /Refresh readiness/);
  assert.match(operationsScreen, /Refresh blockers/);
  assert.match(operationsScreen, /Register current token/);
  assert.match(operationsScreen, /Fix token first/);
  assert.match(operationsScreen, /Local late-alarm preview/);
  assert.match(operationsScreen, /Preview must-catch late alarm/);
  assert.match(operationsScreen, /Stop local preview/);
  assert.match(operationsScreen, /Foreground only while the app is open/);
  assert.match(operationsScreen, /Run test push/);
  assert.match(operationsScreen, /FCM auth health/);
  assert.match(operationsScreen, /Push provider config/);
  assert.match(operationsScreen, /Save device settings/);
  assert.match(operationsScreen, /Current push preview/);
  assert.match(operationsScreen, /Latest push gateway attempt/);
  assert.match(operationsScreen, /TOKEN REFRESH REQUIRED/);
  assert.match(operationsScreen, /Provider category/);
  assert.match(operationsScreen, /Token action/);
  assert.match(operationsScreen, /Refresh and register this phone token/);
  assert.match(operationsScreen, /Run manual test push/);
  assert.match(operationsScreen, /run-push-gateway/);
  assert.match(operationsScreen, /_runCurrentGatewayDispatch/);
  assert.match(operationsScreen, /Dispatch current live bundle/);
  assert.match(operationsScreen, /Seed retryable failure/);
  assert.match(operationsScreen, /Run due retry/);
  assert.match(operationsScreen, /Retry queue/);
  assert.match(operationsScreen, /Top attention/);
  assert.match(operationsScreen, /Top issue/);
  assert.match(operationsScreen, /Instability watch/);
  assert.match(operationsScreen, /Reinforced watch today/);
  assert.match(operationsScreen, /Immediate issue/);
  assert.match(operationsScreen, /Immediate action/);
  assert.match(operationsScreen, /Immediate status/);
  assert.match(operationsScreen, /Strongest outcome/);
  assert.match(operationsScreen, /Playback plan/);
  assert.match(operationsScreen, /Delivery path/);
  assert.match(operationsScreen, /Recorded from/);
  assert.match(operationsScreen, /Open accuracy watchlist/);
  assert.match(operationsScreen, /Open device push health/);
  assert.match(operationsScreen, /Open device details/);
  assert.match(operationsScreen, /Overview action status/);
  assert.match(operationsScreen, /Top routes/);
  assert.match(operationsScreen, /Outcome mix/);
  assert.match(apiClient, /\/api\/auth\/session/);
  assert.match(apiClient, /\/api\/profile/);
  assert.match(apiClient, /\/api\/route/);
  assert.match(apiClient, /\/api\/schedule/);
  assert.match(apiClient, /\/api\/notification-settings/);
  assert.match(apiClient, /\/api\/alarm-runtime/);
  assert.match(apiClient, /\/api\/bus\/accuracy\/leaderboard/);
  assert.match(apiClient, /\/api\/places\/search/);
  assert.match(apiClient, /\/api\/bus\/stations/);
  assert.match(apiClient, /\/api\/bus\/station-routes/);
  assert.match(apiClient, /\/api\/commute\/config/);
  assert.match(apiClient, /\/api\/mobile\/health/);
  assert.match(apiClient, /\/api\/device-profile\/token-health/);
  assert.match(apiClient, /\/api\/device-profile\/register-token/);
  assert.match(apiClient, /\/api\/push-gateway\/config/);
  assert.match(apiClient, /\/api\/fcm-auth\/status/);
  assert.match(apiClient, /\/api\/push-preview/);
  assert.match(apiClient, /\/api\/push-gateway\/attempts/);
  assert.match(apiClient, /\/api\/push-gateway\/test-dispatch/);
  assert.match(apiClient, /\/api\/push-gateway\/dispatch/);
  assert.match(apiClient, /\/api\/push-gateway\/retry-simulation/);
  assert.match(apiClient, /updateBaseUrlAndPersist/);
  assert.match(apiClient, /restorePersistedBaseUrl/);
  assert.match(apiClient, /restorePersistedSession/);
  assert.match(apiClient, /clearSessionCookie/);
  assert.match(apiClient, /Release builds require an HTTPS server URL/);
  assert.match(apiClient, /Duration\(seconds: 8\)/);
  assert.match(apiClient, /connectionTimeout = _requestTimeout/);
  assert.match(apiClient, /http:\/\/\$trimmed/);
  assert.match(apiClient, /Invalid server URL\. Use a format like http:\/\/127\.0\.0\.1:4173 or http:\/\/192\.168\.0\.10:4173\./);
  assert.match(settingsStore, /mobile_api_base_url/);
  assert.match(settingsStore, /mobile_real_device_flow_checkpoint/);
  assert.match(settingsStore, /loadRealDeviceFlowCheckpoint/);
  assert.match(settingsStore, /saveRealDeviceFlowCheckpoint/);
  assert.match(settingsStore, /clearRealDeviceFlowCheckpoint/);
  assert.match(settingsStore, /mobile_real_device_flow_reset_baseline/);
  assert.match(settingsStore, /loadRealDeviceFlowResetBaseline/);
  assert.match(settingsStore, /saveRealDeviceFlowResetBaseline/);
  assert.match(settingsStore, /clearRealDeviceFlowResetBaseline/);
  assert.match(settingsStore, /SharedPreferencesAsync/);
  assert.match(sessionStore, /FlutterSecureStorage/);
  assert.match(sessionStore, /mobile_auth_session_cookie/);
});






